### ISSUE TITLE
Insecure storage

### ISSUE THREAD

**Issue by PEMapModder** [CyberCube-hk/LoginSecurityPE#1]
Issue
===
Passwords should be saved in hash form, and logging in should check the hash form of the input against the saved value.

Examples
===
Examples of converting a strong `$string` into hash form:

```php
md5($string) # used by lbsg. It is faster to hash in this way, but actually the difference with the one below is negligible when players login. However if someone tries to break the password with brute force, this difference matters, so md5 isn't a secure one but still better than none.
hash("sha512", $string) # outputs a 128-byte string of 0-F
hash("whirlpool", $string) # outputs a 128-byte string of 0-F
bin2hex(hash("sha512", $string, true) ^ hash("whirlpool", $string, true)) # used by SimpleAuth, combines the two methods above and outputs a 128-byte string of 0-F. Very secure and not much effect in performance.
```

Reason
===
Hashing passwords can help servers to avoid leaking passwords, both to themselves and to potential hackers (this includes people who somehow steal access to the server harddisk).

**Comment by hoyinm** [comment]
You mean something like this when the player enter their password to login?
if(hash('md5', $password') == $password_from_yml ){
//something
}

**Comment by hoyinm** [comment]
Haha I just 懶得 make it

**Comment by PEMapModder** [comment]
Yep. Also I forgot to add, if you add a salt in front of or after the password, it would be more secure. The salt can be something unique and constant to that player, like his case-insensitive name or a user ID you gave him (if there is one).

**Comment by hoyinm** [comment]
Oic

**Comment by hoyinm** [comment]
Okay I added hash to 0.4_final, it will be posted to github soon when I have time.  (I use my phone to develop plugins)
